### ISSUE TITLE
Search doesn't work anymore

### ISSUE THREAD

**Issue by BTWS2** [dodona-edu/dodona-edu.github.io#156] opened 2021-06-29 11:35 UTC
![image](https://user-images.githubusercontent.com/56451049/123790418-98090780-d8de-11eb-8e4d-25c0fc173e5d.png)

**Comment by bmesuere** [comment] 2021-06-29 12:36
I emailed the algolia helpdesk because the issue seems to be at their side.

**Comment by bmesuere** [comment] 2021-07-01 14:17
This was caused by our domain name switch. Will be fixed after the next indexing round.

**Closed by bmesuere** 2021-07-01 14:17 UTC
